hardcoded_fixes = {
    "malioboro ya ca n malioboro caca": "jalan malioboro",
    "ya ca malioboro caca ca": "jalan malioboro",
    "malioboro ya ca sumini caca": "jalan malioboro",
    "maya malioboro ny aw aj a": "jalan malioboro",
    "maya malioboro wa": "jalan malioboro",
    "maya malioboro ya ja pa wa": "jalan malioboro",
    "maya jalan wa": "jalan malioboro",
    "maya malioboro ya ja": "jalan malioboro",
    "maya malioboro ya wa ja": "jalan malioboro",
    "maya malioboro ny aw a": "jalan malioboro",
    "maya malioboro ny ap aw a": "jalan malioboro",
    "maya jalan ca sumini wa ja": "jalan malioboro",
    "maya jalan sumini ja": "jalan malioboro",
    "maya jalan ca wa ja": "jalan malioboro",
    "jalan na jalan parangtritis": "jalan parangtritis",
    "jalan nata jalan parangtritis": "jalan parangtritis",
    "jalan ta ny at ak a": "jalan parangtritis",
    "jalan na ca tata ny a": "jalan parangtritis",
    "jalan nata ta ca": "jalan parangtritis",
    "jalan nata ta ka": "jalan parangtritis",
    "jalan ta jalan parangtritis": "jalan parangtritis",
    "jalan kaliurang malioboro": "jalan kaliurang",
    "jalan kaliurang malioboro ya": "jalan kaliurang",
    "jalan kaliurang yanya": "jalan kaliurang",
    "jalan kaliurang ragu ragu": "jalan kaliurang",
    "jalan kaliurang ragu": "jalan kaliurang",
    "jalan kaliurang ya": "jalan kaliurang",
    "ta raka ra": "tuku",
    "ta caka ca": "tuku",
    "ta": "tuku",
    "na y maca": "sinau maca",
    "n laya j kak": "sinau maca",
    "na maca": "sinau maca",
    "gunung ka jana caca": "gunung sindoro",
    "gunung sindoro caca": "gunung sindoro",
    "sa mana": "sumini",
    "mana": "sumini",
}
